# All module-level configuration constants for quant-compass backend.
# FUND_LIST_CACHE lives in core/data.py (it is runtime state, not config).

DEFAULT_STRATEGY_MODE = "fixed_weight"
VALID_STRATEGY_MODES = {DEFAULT_STRATEGY_MODE}
DEFAULT_ESTIMATION_WINDOW = 36
DEFAULT_CVAR_CONFIDENCE = 0.95
DEFAULT_CVAR_LIMIT = 0.08
DEFAULT_MAX_DRAWDOWN_LIMIT = 0.20
DEFAULT_RISK_HORIZON_DAYS = 21
MIN_CVAR_TAIL_OBSERVATIONS = 5
MIN_SORTINO_DOWNSIDE_OBSERVATIONS = 3
MIN_WALK_FORWARD_EVALUATION_MONTHS = 24
MIN_COVARIANCE_ABLATION_SEGMENT_MONTHS = 12
RETURN_SHRINKAGE = 0.35
COVARIANCE_SHRINKAGE = 0.20
DEFAULT_APPLY_FUND_FEES_TO_HISTORY = False
MIN_WALK_FORWARD_TRAIN_MONTHS = 24

DEFAULT_REBALANCE_BAND = 0.02  # execution tolerance, not a statistical risk limit
